In [2]:
# array 与 list的区别
# array 里面的元素类型要统一，list里面的元素类型可以不一样

# ndarray的创建方法
# list 转换为ndarray
close_list = [10,10.5,11.0,12.0]
close_list

[10, 10.5, 11.0, 12.0]

In [3]:
import numpy as np
# list转换为ndarray
close_array = np.array(close_list)
close_array

array([10. , 10.5, 11. , 12. ])

In [4]:
# 将元组转化为ndarray
stock_info_tuple = ('000001','平安银行','bank')
stock_info_array = np.array(stock_info_tuple)
stock_info_array

array(['000001', '平安银行', 'bank'], dtype='<U6')

In [5]:
# 使用迭代器生成ndarray
range_iterator = range(5)
range_array = np.array(range_iterator)
range_array

array([0, 1, 2, 3, 4])

In [6]:
# 生成两维数组
range_array = np.array((range_iterator,range_iterator))
range_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [7]:
range_array = np.array([range_iterator,range_iterator])
range_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [8]:
# 创建一个全是1的矩阵
ones_array = np.ones((2,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# 使用np.ones_like()创建多纬array,复制的是矩阵结构
ones_like_array = np.ones_like(ones_array)
ones_like_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 创建没有指定初始化的ndarray
empty_array = np.empty((3,4))
empty_array

array([[1.1111228e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [11]:
# 转换元素为整型
empty_array = np.empty((3,4),dtype='i')
empty_array

array([[         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248]], dtype=int32)

In [12]:
# 创建等差数列
linspace_array = np.linspace(5,15,10)

In [13]:
# 计算并打印输出该股票在这段时间内的5日移动平均数据
data = {'2016/10/10':12.57, '2016/10/11':12.58, '2016/10/12':12.53, '2016/10/13':12.47,
'2016/10/14':12.51, '2016/10/17':12.35, '2016/10/18':12.41, '2016/10/19':12.35,
'2016/10/20':12.37, '2016/10/21':12.38, '2016/10/24':12.59, '2016/10/25':12.41,
'2016/10/26':12.39, '2016/10/27':12.26, '2016/10/28':12.32, '2016/10/31':12.35}

import pandas as pd

s = pd.Series(data)
s

2016/10/10    12.57
2016/10/11    12.58
2016/10/12    12.53
2016/10/13    12.47
2016/10/14    12.51
2016/10/17    12.35
2016/10/18    12.41
2016/10/19    12.35
2016/10/20    12.37
2016/10/21    12.38
2016/10/24    12.59
2016/10/25    12.41
2016/10/26    12.39
2016/10/27    12.26
2016/10/28    12.32
2016/10/31    12.35
dtype: float64

In [14]:
s_mean = s.rolling(5).mean()
s_mean

2016/10/10       NaN
2016/10/11       NaN
2016/10/12       NaN
2016/10/13       NaN
2016/10/14    12.532
2016/10/17    12.488
2016/10/18    12.454
2016/10/19    12.418
2016/10/20    12.398
2016/10/21    12.372
2016/10/24    12.420
2016/10/25    12.420
2016/10/26    12.428
2016/10/27    12.406
2016/10/28    12.394
2016/10/31    12.346
dtype: float64

In [19]:
# 计算5日均线值和20日均线，移动平均策略
data = {
    'MA_5': [15,13,10,10,13],
    'MA_20': [10,11,12,13,12]
}

df = pd.DataFrame(data=data,index=['2018-01-01','2018-01-02','2018-01-03','2018-01-04','2018-01-05'])
df

MA_5  MA_20
2018-01-01    15     10
2018-01-02    13     11
2018-01-03    10     12
2018-01-04    10     13
2018-01-05    13     12

In [20]:
df['position'] = np.where(df['MA_5']>df['MA_20'],1,-1)
df

MA_5  MA_20  position
2018-01-01    15     10         1
2018-01-02    13     11         1
2018-01-03    10     12        -1
2018-01-04    10     13        -1
2018-01-05    13     12         1

In [ ]:
# 现要求产生一列新数据作为交易信号保存在factor_data新建的一列上,列名为'signal',当同时满足五日均线大于20日均线,20日均线大于60日均线时,信号列数据为1,其他情况信号列数据全为0。
factor_data['signal'] = np.where((factor_data['MA_5'] > factor_data['MA_20']) & (factor_data['MA_20'] > factor_data['MA_60']),1,0)