In [1]:
# array 与 list的区别
# array 里面的元素类型要统一，list里面的元素类型可以不一样

# ndarray的创建方法
# list 转换为ndarray
close_list = [10,10.5,11.0,12.0]
close_list

[10, 10.5, 11.0, 12.0]

In [2]:
import numpy as np
# list转换为ndarray
close_array = np.array(close_list)
close_array

array([10. , 10.5, 11. , 12. ])

In [3]:
# 将元组转化为ndarray
stock_info_tuple = ('000001','平安银行','bank')
stock_info_array = np.array(stock_info_tuple)
stock_info_array

array(['000001', '平安银行', 'bank'], dtype='<U6')

In [5]:
# 使用迭代器生成ndarray
range_iterator = range(5)
range_array = np.array(range_iterator)
range_array

array([0, 1, 2, 3, 4])

In [6]:
# 生成两维数组
range_array = np.array((range_iterator,range_iterator))
range_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [7]:
range_array = np.array([range_iterator,range_iterator])
range_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [8]:
# 创建一个全是1的矩阵
ones_array = np.ones((2,3))
ones_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# 使用np.ones_like()创建多纬array,复制的是矩阵结构
ones_like_array = np.ones_like(ones_array)
ones_like_array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
# 创建没有指定初始化的ndarray
empty_array = np.empty((3,4))
empty_array

array([[1.49166815e-154, 1.49166815e-154, 3.95252517e-323,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [11]:
# 转换元素为整型
empty_array = np.empty((3,4),dtype='i')
empty_array

array([[         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248],
       [         0, 1072693248,          0, 1072693248]], dtype=int32)

In [ ]:
# 创建等差数列
linspace_array = np.linspace(5,15,10)