In [1]:
# 引包
import numpy as np

close_array = np.array([10,10.5,11.0,11.5,12.0])
close_array

array([10. , 10.5, 11. , 11.5, 12. ])

In [2]:
# 选择array里面的第一个元素
close_array[0]

10.0

In [3]:
# 选择array里面的最后一个元素
close_array[-1]

12.0

In [4]:
# 选择其中一段元素,[)区间，前闭后开区间
close_array[2:4]

array([11. , 11.5])

In [5]:
# 从第一个元素到第五个元素
close_array[1:5:2]

array([10.5, 11.5])

In [6]:
# 切片操作
volume_stock1 = [10,20,10,15,20]
volume_stock2 = [25,39,45,89,100]
volume_stock3 = [55,35,10,20,30]

In [7]:
volume_matrix = np.array([volume_stock1,volume_stock2,volume_stock3])
volume_matrix

array([[ 10,  20,  10,  15,  20],
       [ 25,  39,  45,  89, 100],
       [ 55,  35,  10,  20,  30]])

In [8]:
# 获取所有股票第一天的交易量
volume_matrix[:,1]

array([20, 39, 35])

In [9]:
# 所有股票前两天的交易量
volume_matrix[:,:2]

array([[10, 20],
       [25, 39],
       [55, 35]])

In [10]:
# 选择前两只股票，后三天的交易量
volume_matrix[:2,-3:]

array([[ 10,  15,  20],
       [ 45,  89, 100]])

In [12]:
#  所有股票，奇数天交易量
volume_matrix[:,::2]

array([[ 10,  10,  20],
       [ 25,  45, 100],
       [ 55,  10,  30]])

In [14]:
volume_matrix[:,[0,2,4]]

array([[ 10,  10,  20],
       [ 25,  45, 100],
       [ 55,  10,  30]])