In [1]:
# 引包
import numpy as np

In [2]:
return_list = [0.05,-0.10,0.10,0.15]
return_list * 2

[0.05, -0.1, 0.1, 0.15, 0.05, -0.1, 0.1, 0.15]

In [3]:
# 向量化
return_from_stock = np.array([0.01,0.12,0.3,0.06,-0.05])
return_from_stock

array([ 0.01,  0.12,  0.3 ,  0.06, -0.05])

In [4]:
# 遍历数组
[i * 2 for i in return_list]

[0.1, -0.2, 0.2, 0.3]

In [8]:
# 向量化计算
return_array = np.array([10,10.5,11.0,11.5,12.0])
leverage_array = np.array([2,1.5,1.8,2.2,2.5])

return_array + return_array

array([20., 21., 22., 23., 24.])

In [6]:
return_array * return_array

array([100.  , 110.25, 121.  , 132.25, 144.  ])

In [9]:
# 对应位置的元素进行计算
return_array / leverage_array

array([5.        , 7.        , 6.11111111, 5.22727273, 4.8       ])

In [10]:
# 测试两种计算表示的性能
#（1）[i for i in array]
data_array = np.random.standard_normal(1000000)
data_array

array([-1.29332314,  0.42258928,  1.52017731, ...,  1.38460085,
        0.26360308,  1.38283315])

In [11]:
data_list = list(data_array)

In [12]:
%timeit [i*2 for i in data_list]

247 ms ± 6.77 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
%timeit 2* data_array

564 µs ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### 可以看出使用第一种方案的执行效率要比第二种高