In [1]:
import numpy as np

# ndarray创建方法补充
r = np.random.standard_normal((4,3))
s = np.random.standard_normal([4,3])

In [2]:
# 锁定产生的随机数
np.random.seed(32)
s = np.random.standard_normal([4,3])
s

array([[-0.34889445,  0.98370343,  0.58092283],
       [ 0.07028444,  0.77753268,  0.58195875],
       [ 1.47179053,  1.66318101, -0.26117712],
       [-0.68867681, -0.69492326,  1.94042346]])

In [4]:
np.random.seed(10)
t = np.random.standard_normal([4,3])
t

array([[ 1.3315865 ,  0.71527897, -1.54540029],
       [-0.00838385,  0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853,  0.00429143],
       [-0.17460021,  0.43302619,  1.20303737]])

In [5]:
# broadcast 广播
stock_pe = np.array(
    [
        [15,16,17,18,19],
        [50,51,52,53,54],
        [20,18,19,17,15],
    ]
)

stock_position = np.array(
    [
        [10,15,20,30],
        [20,20,25,20],
        [10,10,10,11]
    ]
)

In [6]:
pe_average = np.average(stock_pe)
pe_average

28.933333333333334

In [7]:
pe_std = np.std(stock_pe)
pe_std

16.384816819916608

In [8]:
# 标准化
pe_standardized = (stock_pe - pe_average) / pe_std
pe_standardized

array([[-0.85038078, -0.78934867, -0.72831655, -0.66728444, -0.60625233],
       [ 1.28574319,  1.3467753 ,  1.40780742,  1.46883953,  1.52987165],
       [-0.54522021, -0.66728444, -0.60625233, -0.72831655, -0.85038078]])