In [1]:
import numpy as np

# 累计计算
income_array = np.array([10,20,30,40])

# 累计求和
income_array.cumsum()

array([ 10,  30,  60, 100])

In [2]:
# 累计求积
daily_return = np.array([0.1,0.05,-0.01,0.02])

daily_return += 1
daily_return

array([1.1 , 1.05, 0.99, 1.02])

In [3]:
daily_return.cumprod()

array([1.1     , 1.155   , 1.14345 , 1.166319])

In [4]:
# np.where 条件判断
facotr = np.random.randn(3,5)
facotr

array([[ 0.09564562, -0.60984427,  0.46173475, -1.31698314,  0.00421363],
       [-0.48916052,  0.28569608,  0.51315413,  0.2066091 ,  0.09037167],
       [-0.7758351 , -1.89312167, -0.21632815,  0.42919154,  0.58337878]])

In [5]:
signal = np.where(facotr > 0.2,1,0)
signal

array([[0, 0, 1, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1]])

In [6]:
#  检查是否存在一个True
np.any(np.array([True,False]))

True

In [7]:
# 检查是否全部存在True
np.all(np.array([True,False]))

False

In [8]:
# numpy.random.choice(a,size=None,replace=True,p=None)
# 从给定的一维数组中生成随机数
# 参数：a为一维数组类似于数据或整数；size为数组纬度，p为数组中的数据出现次数
np.random.choice(10,8)

array([7, 8, 5, 4, 5, 4, 4, 3])

In [9]:
demo_list = ['lenovo','sansumg','moto','xiaomi','iphone']
np.random.choice(demo_list,size=(3,3),p=[0.1,0.6,0.1,0.1,0.1])

array([['sansumg', 'xiaomi', 'sansumg'],
       ['sansumg', 'sansumg', 'iphone'],
       ['lenovo', 'sansumg', 'lenovo']], dtype='<U7')